import WelcomeModal from '@/components/modals/welcome-modal'
import './globals.css'
import type { Metadata } from 'next'
import { Space_Mono } from 'next/font/google'
import ModalProvider from '@/providers/modal-provider'

const spaceMono = Space_Mono({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={spaceMono.className}>
        <ModalProvider/>
        {children}
      </body>
    </html>
  )
}
